name: PHP Config
description: Add PHP level configurations
package: Development
type: module
# version: 1.0
# core: 8.x
# Information added by Drupal.org packaging script on 2018-08-07
version: '8.x-1.1'
core: '8.x'
project: 'phpconfig'
datestamp: 1533672786
